name: Build Android

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.17.1
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.1
        cache: 'npm'
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: npm ci
    # create www folder to satisfy cordova
    - run: mkdir -p www
    - run: npm run cordova -- platform add android
    - run: npm run ionic -- cordova build android
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "Android Debug APK"
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
